//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International_Widgets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<double> OrderTotalPrice { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
