//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International_Widgets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int InvoiceID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<int> ItemTotal { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
    }
}
